---
# Source: sentry/charts/rabbitmq/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentry-rabbitmq
  namespace: "sentry"
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/version: "3.11.18"
automountServiceAccountToken: true
secrets:
  - name: sentry-rabbitmq
