---
# Source: sentry/templates/snuba/deployment-snuba-api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-snuba-api
  labels:
    app: sentry
    chart: "sentry-27.2.4"
    release: "sentry"
    heritage: "Helm"
    app.kubernetes.io/name: sentry
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/component: snuba-api
    app.kubernetes.io/version: "25.8.0"
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sentry
      release: "sentry"
      role: snuba-api
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: d5f85a6a8afbc55eebe23801e1a51a0fb4c0428c9a73ef6708d8dc83e079cd49
        checksum/config.yaml: 5c8d42182f979a9f396975353f1b4f7c58ed658819a1fd6b8cf375c4757193ec
      labels:
        app: sentry
        release: "sentry"
        role: snuba-api
        app.kubernetes.io/name: sentry
        app.kubernetes.io/instance: sentry
        app.kubernetes.io/component: snuba-api
        app.kubernetes.io/version: "25.8.0"
    spec:
      affinity:
      containers:
        - name: sentry-snuba
          image: "ghcr.io/getsentry/snuba:25.8.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1218
          env:
            - name: SNUBA_SETTINGS
              value: /etc/snuba/settings.py
            - name: DEFAULT_BROKERS
              value: "sentry-kafka:9092"
            - name: KAFKA_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: CLICKHOUSE_MAX_CONNECTIONS
              value: "100"
            - name: REDIS_PORT
              value: "6379"
          envFrom:
            - secretRef:
                name: sentry-snuba-env
          volumeMounts:
            - mountPath: /etc/snuba
              name: config
              readOnly: true
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 1218
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 1218
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources: {}
      volumes:
        - name: config
          configMap:
            name: sentry-snuba
