---
# Source: sentry/charts/redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: sentry-sentry-redis
  namespace: "sentry"
  labels:
    app.kubernetes.io/name: sentry-redis
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/version: "7.0.11"
