---
# Source: sentry/charts/kafka/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sentry-kafka
  namespace: "sentry"
  labels:
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.7.1
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: sentry
      app.kubernetes.io/name: kafka
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    # Allow client connections
    - ports:
        - port: 9092
        - port: 9094
        - port: 9093
