---
# Source: sentry/charts/kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sentry-kafka-kraft-cluster-id
  namespace: "sentry"
  labels:
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.7.1
type: Opaque
data:
  kraft-cluster-id: "T3hmWWdVZHBMbGd4dXFPdVFENVNNSQ=="
