---
# Source: sentry/templates/relay/service-relay.yaml
apiVersion: v1
kind: Service
metadata:
  name: sentry-relay
  annotations:
  labels:
    app: sentry
    chart: "sentry-27.2.4"
    release: "sentry"
    heritage: "Helm"
    app.kubernetes.io/name: sentry
    app.kubernetes.io/instance: sentry
    app.kubernetes.io/component: relay
    app.kubernetes.io/version: "25.8.0"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: sentry-relay
  selector:
    app: sentry
    role: relay
